export const en = {
  //  ui labels
  app: 'KP MASTER PLAN',
  signin: 'Signin',
  signup: 'Signup',
  email: 'Email',
  password: 'Password',
  confirm_pass: 'Confirm password',
  phone: 'Phone number',
  forgot_pass: 'Forgot password',
  already_have_acc: 'Already have account?',
  create_new_acc: `Create new account`,
  no_acc: `Don't have account?`,
  create: 'Create',
  close: 'Close',
  search: 'Search',
  search_friend: 'User ID/Phone Number',
  new_contact: 'New Contact',
  invite: 'Invite',
  address: 'Address',
  building: 'Building',
  loading: 'Loading...',
  //alerts
  invalid: 'Inputh valid values!',
  same_pass: 'Input the same password',
};
export const ar = {
  //  ui labels
  app: 'PLANI MASTER i PK-së',
  signin: 'Hyni',
  signup: 'Regjistrohu',
  email: 'Email',
  password: 'fjalëkalim',
  confirm_pass: 'konfirmoni fjalëkalimin',
  phone: 'Numri i telefonit',
  forgot_pass: 'keni harruar fjalëkalimin',
  already_have_acc: 'Tashmë keni llogari?',
  create_new_acc: `hapni një llogari të re`,
  no_acc: `nuk keni llogari`,
  create: 'krijoj',
  close: 'afër',
  search: 'Kërko',
  new_contact: 'Kontakt i ri',
  invite: 'ftoj',
  address: 'Adresë',
  building: 'ndërtesë',
  loading: 'Loading...',
  //alerts
  invalid: 'vlera të vlefshme hyrëse!',
  same_pass: 'jepni të njëjtin fjalëkalim',
  search_friend: 'ID e përdoruesit / numri i telefonit',
};
