export const en = {
  //  ui labels
  app: 'KP MASTER PLAN',
  signin: 'Signin',
  signup: 'Signup',
  email: 'Email',
  password: 'Password',
  confirm_pass: 'Confirm password',
  phone: 'Phone number',
  forgot_pass: 'Forgot password',
  already_have_acc: 'Already have account?',
  create_new_acc: `Create new account`,
  no_acc: `Don't have account?`,
  create: 'Create',
  close: 'Close',
  search: 'Search',
  search_friend: 'User ID/Phone Number',
  new_contact: 'New Contact',
  invite: 'Invite',
  address: 'Address',
  building: 'Building',
  loading: 'Loading...',
  //alerts
  invalid: 'Input valid values!',
  same_pass: 'Input the same password',
  network_error: 'Network error!',
  success: 'Success!',
  error: 'Error!',
  self_email: `Can't add your account!`,
  reject: 'Reject!',
  car_saved: 'Saved the car location!',
  car_not_saved: 'Not saved the car location!',
  not_selected_friend: 'Not selected the friend!',
};
export const ar = {
  //  ui labels
  app: 'PLANI MASTER i PK-së',
  signin: 'Hyni',
  signup: 'Regjistrohu',
  email: 'Email',
  password: 'fjalëkalim',
  confirm_pass: 'konfirmoni fjalëkalimin',
  phone: 'Numri i telefonit',
  forgot_pass: 'keni harruar fjalëkalimin',
  already_have_acc: 'Tashmë keni llogari?',
  create_new_acc: `hapni një llogari të re`,
  no_acc: `nuk keni llogari`,
  create: 'krijoj',
  close: 'afër',
  search: 'Kërko',
  search_friend: 'ID e përdoruesit / numri i telefonit',
  new_contact: 'Kontakt i ri',
  invite: 'ftoj',
  address: 'Adresë',
  building: 'ndërtesë',
  loading: 'Loading...',
  //alerts
  invalid: 'vlera të vlefshme hyrëse!',
  same_pass: 'jepni të njëjtin fjalëkalim',
  network_error: 'Gabim në rrjet!',
  success: 'sukses!',
  error: 'gabim!',
  self_email: 'Nuk mund të shtoni llogarinë tuaj!',
  reject: 'hedh poshtë!',
  car_saved: 'Saved the car location!',
  car_not_saved: 'Nuk e ruajti vendndodhjen e makinës!',
  not_selected_friend: 'Nuk u zgjodh miku!',
};
